### ISSUE TITLE
建议增加位置选项，可以采用正下方或相对位置。

### ISSUE THREAD

**Issue by mylater** [TangHanF/layui_plugin#6]
使用
-------------------
 rightmenu_.render({
            container: '#layadmin-pagetabs',
            filter: 'layuiTab',
            width: 110,
            // down relative
            position: 'down',
            // navArr：对象数组，每个对象包含dataType、title、method属性
            navArr: [
                {eventName: 'closethis', title: '关闭当前', icon: 'layui-icon-close'},
                {eventName: 'closeall', title: '关闭所有'},
                {eventName: 'closeothers', title: '关闭其它'},
                {eventName: 'closeleftbutpin', title: '关闭左侧'},
                {eventName: 'closerightbutpin', title: '关闭右侧'},
                //{eventName: 'line'}// 创建分割线
            ],
            // 注册自定义事件
            registMethod: {'test': testMethod, 'test2': test2Method}
        })

tabrightmenu.js#_CustomRightClick()
-------------------
   if (rightMenuConfig.position === 'down') {
                leftValue = $(e.target).offset().left;
                topValue = $(e.target).offset().top + $(e.target)[0].clientHeight;
            } else {
                leftValue = ($(document).width() - e.clientX) < popupmenu.width() ? (e.clientX - popupmenu.width()) : e.clientX;
                topValue = ($(document).height() - e.clientY) < popupmenu.height() ? (e.clientY - popupmenu.height()) : e.clientY;
            }

**Comment by TangHanF** [comment]
感谢，已采纳并合并！
